// <auto-generated />
using GreenThumb.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenThumb.Models.Instructions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("instructions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instruction = "Need Sunight",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Instruction = "Need Sunlight",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 3,
                            Instruction = "Need Sunlight",
                            PlantId = 4
                        },
                        new
                        {
                            Id = 4,
                            Instruction = "Need Sunlight",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 5,
                            Instruction = "Need Sunlight",
                            PlantId = 6
                        },
                        new
                        {
                            Id = 6,
                            Instruction = "Need Sunlight",
                            PlantId = 7
                        },
                        new
                        {
                            Id = 7,
                            Instruction = "Need Sunlight",
                            PlantId = 9
                        },
                        new
                        {
                            Id = 8,
                            Instruction = "Need Sunlight",
                            PlantId = 10
                        },
                        new
                        {
                            Id = 9,
                            Instruction = "Need Water",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 10,
                            Instruction = "Need Water",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 11,
                            Instruction = "Need Water",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 12,
                            Instruction = "Need Water",
                            PlantId = 4
                        },
                        new
                        {
                            Id = 13,
                            Instruction = "Need Water",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 14,
                            Instruction = "Need Water",
                            PlantId = 6
                        },
                        new
                        {
                            Id = 15,
                            Instruction = "Need Water",
                            PlantId = 7
                        },
                        new
                        {
                            Id = 16,
                            Instruction = "Need Water",
                            PlantId = 8
                        },
                        new
                        {
                            Id = 17,
                            Instruction = "Need Water",
                            PlantId = 9
                        },
                        new
                        {
                            Id = 18,
                            Instruction = "Need Water",
                            PlantId = 10
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.Plants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tomatoes: Versatile, juicy fruits rich in vitamins. Used in salads, sauces, and various dishes worldwide for their sweet-tangy flavor and vibrant colors.",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Carrot is a biennial, belonging to the family Apiaceae, and is an important vegetable for its fleshy edible, colorful roots",
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Blueberris,Small, sweet, and purple. Packed with antioxidants, vitamins C and K. Good for the heart and brain. Used in baking and smoothies.",
                            Name = "Blueberry"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Juicy, sweet, with fuzzy skin. Rich in vitamins A and C. Great fresh or in desserts.",
                            Name = "Peach"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lemons: Tangy citrus fruits rich in vitamin C. Used in cooking, baking, and beverages for a refreshing flavor",
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Coconuts: Large brown fruits with sweet water and creamy flesh. Used in cooking, desserts, and beverages. Rich in nutrients and versatile in various cuisines",
                            Name = "Coconut"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Watermelon: Juicy, sweet fruit with red flesh and high water content. Refreshing and hydrating summer treat. Rich in vitamins and antioxidants. Enjoyed fresh or in beverages and salads",
                            Name = "Watermelon"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Pears: Sweet, juicy fruits with a soft texture. Available in various colors. Rich in fiber, vitamins, and antioxidants. Enjoy fresh or in diverse recipes",
                            Name = "Pear"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Grapes: Small, sweet fruits in various colors. Juicy and packed with vitamins and antioxidants. Eaten fresh, used in salads, or made into wine and raisins",
                            Name = "Grape"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Oranges: Tangy-sweet citrus fruits, rich in vitamin C and antioxidants. Enjoy fresh, juiced, or in cooking for a refreshing taste and health benefits",
                            Name = "Orange"
                        });
                });

            modelBuilder.Entity("GreenThumb.Models.Instructions", b =>
                {
                    b.HasOne("GreenThumb.Models.Plants", "Plant")
                        .WithMany("instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb.Models.Plants", b =>
                {
                    b.Navigation("instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
